[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "spd-2026"
authors = [
    {name = "Roy T. Smart", email = "roytsmart@gmail.com"},
]
description = "A presentation on the physical structure and evolution of transition region explosive events observed with ESIS."
readme = "readme.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "matplotlib",
    "astropy",
    "joblib",
    "named-arrays",
    "colorsynth",
    "interface-region-imaging-spectrograph",
    "euv-snapshot-imaging-spectrograph",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
]

[project.urls]
Homepage = "https://github.com/roytsmart/spd-2026"

[tool.setuptools_scm]

[tool.setuptools.packages.find]
where = ["src"]
